<a href="https://colab.research.google.com/github/kirbytreat/lazypredict/blob/master/boilerlazypredict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#import lazyprecict from pip or github repo https://github.com/shankarpandala/lazypredict
pip install lazypredict

SyntaxError: ignored

In [4]:
import lazypredict

In [6]:
#import data from local machine will give you a prompt to select file
from google.colab import files
uploaded = files.upload()

Saving data (37).csv to data (37) (1).csv

In [7]:
# turn data into a dataframe
import io
import pandas as pd
df1 = pd.read_csv(io.BytesIO(uploaded['data (37).csv']))

In [8]:
df1

                       Timestamp  ...  TOTAL___TOTAL_STEAM_FLOW_CONSUMERS
0       2020-06-21T05:00:06.437Z  ...                              117.90
1       2020-06-21T05:00:16.446Z  ...                              117.89
2       2020-06-21T05:00:26.627Z  ...                              110.47
3       2020-06-21T05:00:36.715Z  ...                              109.91
4       2020-06-21T05:00:47.094Z  ...                              109.17
...                          ...  ...                                 ...
641088  2020-08-07T19:01:39.864Z  ...                                 nan
641089  2020-08-07T19:01:46.466Z  ...                               41.92
641090  2020-08-07T19:01:50.099Z  ...                                 nan
641091  2020-08-07T19:01:56.778Z  ...                               39.35
641092  2020-08-07T19:02:00.313Z  ...                                 nan

[641093 rows x 34 columns]

In [9]:
df1.shape

(641093, 34)

In [10]:
df1.dtypes

Timestamp                                             object
BOILER_1___AFTER_ECONOMIZER_FLUE_GAS_TEMPERATURE     float64
BOILER_1___BEFORE_ECONOMIZER_FLUE_GAS_TEMPERATURE    float64
BOILER_1___FEEDWATER_FLOW                            float64
BOILER_1___FEEDWATER_INLET_TEMPERATURE               float64
BOILER_1___FLUE_GAS_O2_ANALYZER                      float64
BOILER_1___NATURAL_GAS_FLOW                          float64
BOILER_1___STEAM_DRUM_PRESSURE                       float64
BOILER_2___AFTER_ECONOMIZER_FLUE_GAS_TEMPERATURE     float64
BOILER_2___BEFORE_ECONOMIZER_FLUE_GAS_TEMPERATURE    float64
BOILER_2___FEEDWATER_FLOW                            float64
BOILER_2___FEEDWATER_INLET_TEMPERATURE               float64
BOILER_2___FLUE_GAS_O2_ANALYZER                      float64
BOILER_2___NATURAL_GAS_FLOW                          float64
BOILER_2___STEAM_DRUM_PRESSURE                       float64
BOILER_4___AFTER_ECONOMIZER_FLUE_GAS_TEMPERATURE     float64
BOILER_4___BEFORE_ECONOMIZER_FLUE_GAS_TEMPERATURE    float64
BOILER_4___FEEDWATER_FLOW                            float64
BOILER_4___FEEDWATER_INLET_TEMPERATURE               float64
BOILER_4___FLUE_GAS_O2_ANALYZER                      float64
BOILER_4___NATURAL_GAS_FLOW                          float64
BOILER_4___STEAM_DRUM_PRESSURE                       float64
BOILER_5___AFTER_ECONOMIZER_FLUE_GAS_TEMPERATURE     float64
BOILER_5___BEFORE_ECONOMIZER_FLUE_GAS_TEMPERATURE    float64
BOILER_5___FEEDWATER_FLOW                            float64
BOILER_5___FEEDWATER_INLET_TEMPERATURE               float64
BOILER_5___FLUE_GAS_O2_ANALYZER                      float64
BOILER_5___NATURAL_GAS_FLOW                          float64
BOILER_5___STEAM_DRUM_PRESSURE                       float64
CONSUMER___BOILER_MASTER_STEAM_HEADER_PV             float64
TOTAL___BIO_GAS_FLOW                                 float64
TOTAL___NATURAL_GAS_FLOW                             float64
TOTAL___STEAM_FLOW                                   float64
TOTAL___TOTAL_STEAM_FLOW_CONSUMERS                   float64
dtype: object

In [11]:
# dropped Timestamp because its an Object
df2 = df1
del df2['Timestamp']

In [45]:
df2

        BOILER_1___AFTER_ECONOMIZER_FLUE_GAS_TEMPERATURE  ...  TOTAL___TOTAL_STEAM_FLOW_CONSUMERS
0                                                 133.92  ...                              117.90
1                                                 133.75  ...                              117.89
2                                                 133.75  ...                              110.47
3                                                 133.91  ...                              109.91
4                                                 133.63  ...                              109.17
...                                                  ...  ...                                 ...
641088                                            139.91  ...                                 nan
641089                                               nan  ...                               41.92
641090                                            139.74  ...                                 nan
641091                                               nan  ...                               39.35
641092                                            139.69  ...                                 nan

[641093 rows x 33 columns]

In [12]:
df2.isnull().values.any()

True

In [13]:
df2.isnull().sum().sum()

7897163

In [14]:
df2.isnull()

        BOILER_1___AFTER_ECONOMIZER_FLUE_GAS_TEMPERATURE  ...  TOTAL___TOTAL_STEAM_FLOW_CONSUMERS
0                                                  False  ...                               False
1                                                  False  ...                               False
2                                                  False  ...                               False
3                                                  False  ...                               False
4                                                  False  ...                               False
...                                                  ...  ...                                 ...
641088                                             False  ...                                True
641089                                              True  ...                               False
641090                                             False  ...                                True
641091                                              True  ...                               False
641092                                             False  ...                                True

[641093 rows x 33 columns]

In [15]:
df2.isnull().sum()

BOILER_1___AFTER_ECONOMIZER_FLUE_GAS_TEMPERATURE     239422
BOILER_1___BEFORE_ECONOMIZER_FLUE_GAS_TEMPERATURE    239422
BOILER_1___FEEDWATER_FLOW                            239422
BOILER_1___FEEDWATER_INLET_TEMPERATURE               239422
BOILER_1___FLUE_GAS_O2_ANALYZER                      239422
BOILER_1___NATURAL_GAS_FLOW                          239422
BOILER_1___STEAM_DRUM_PRESSURE                       239422
BOILER_2___AFTER_ECONOMIZER_FLUE_GAS_TEMPERATURE     239422
BOILER_2___BEFORE_ECONOMIZER_FLUE_GAS_TEMPERATURE    239422
BOILER_2___FEEDWATER_FLOW                            239422
BOILER_2___FEEDWATER_INLET_TEMPERATURE               239422
BOILER_2___FLUE_GAS_O2_ANALYZER                      239422
BOILER_2___NATURAL_GAS_FLOW                          239422
BOILER_2___STEAM_DRUM_PRESSURE                       239422
BOILER_4___AFTER_ECONOMIZER_FLUE_GAS_TEMPERATURE     239422
BOILER_4___BEFORE_ECONOMIZER_FLUE_GAS_TEMPERATURE    239422
BOILER_4___FEEDWATER_FLOW                            239422
BOILER_4___FEEDWATER_INLET_TEMPERATURE               239422
BOILER_4___FLUE_GAS_O2_ANALYZER                      239422
BOILER_4___NATURAL_GAS_FLOW                          239422
BOILER_4___STEAM_DRUM_PRESSURE                       239422
BOILER_5___AFTER_ECONOMIZER_FLUE_GAS_TEMPERATURE     239422
BOILER_5___BEFORE_ECONOMIZER_FLUE_GAS_TEMPERATURE    239422
BOILER_5___FEEDWATER_FLOW                            239422
BOILER_5___FEEDWATER_INLET_TEMPERATURE               239422
BOILER_5___FLUE_GAS_O2_ANALYZER                      239422
BOILER_5___NATURAL_GAS_FLOW                          239422
BOILER_5___STEAM_DRUM_PRESSURE                       239422
CONSUMER___BOILER_MASTER_STEAM_HEADER_PV             239422
TOTAL___BIO_GAS_FLOW                                 238481
TOTAL___NATURAL_GAS_FLOW                             238481
TOTAL___STEAM_FLOW                                   238481
TOTAL___TOTAL_STEAM_FLOW_CONSUMERS                   238482
dtype: int64

In [16]:
df3 = df2
df3 = df3.dropna(how='any',axis=0)

In [17]:
df3.shape

(163190, 33)

In [18]:
from lazypredict.Supervised import LazyRegressor
from sklearn.utils import shuffle
import numpy as np
boiler = df3

In [ ]:
X, y = shuffle(boiler, boiler.TOTAL___NATURAL_GAS_FLOW, random_state=13)
X = X.astype(np.float32)
offset = int(X.shape[0] * 0.9)
X_train, y_train = X[:offset], y[:offset]
X_test, y_test = X[offset:], y[offset:]
reg = LazyRegressor(verbose=0,ignore_warnings=False, custom_metric=None )
models,predictions = reg.fit(X_train, X_test, y_train, y_test)

 23%|██▎       | 9/39 [03:15<18:27, 36.91s/it]